version: "3.8"
services:
    # Mysql
    mysqldb:
        container_name: '${PROJECT_NAME}-mysqldb'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        image: mysql
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./mysql-volume:/var/lib/mysql
        command: '--default-authentication-plugin=mysql_native_password'
    # Redis
    redis:
        container_name: '${PROJECT_NAME}-redis'
        restart: on-failure
        image: redis:6.0.8
        ports:
            - '${REDIS_PORT}:6379'
    # Nodejs
    app:
        container_name: "${CONTAINER_NAME}-api-service-dev"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        # mount only src folder
        volumes:
            - ./src:/usr/src/app/src
            - ./package.json:/usr/src/app/package.json
        ports:
            - '${M_PORT}:${PORT}'
networks:
    default:
        name: '${NETWORK_NAME}'
